version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: pg_container
    depends_on:
      - etl
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    container_name: etl_container
    #depends_on:
      #- postgres
    env_file:
      - .env
    command: python load.py  # could also run extract.py -> transform.py -> load.py

  streamlit:
    build: .
    container_name: streamlit_container
    depends_on:
      - etl
      - postgres
    ports:
      - "8501:8501"
    env_file:
      - .env
    command: streamlit run streamlit_app.py

volumes:
  pgdata:
